### ISSUE TITLE
RegexReplacementRule: Support Regex Values

### ISSUE THREAD

**Issue by martinschemel** [ingomohr/docwriter#27]
It would be nice if the value returned by the second constructor argument (supplier) supports regular expressions, too (not only the first string argument).

* Example: `new RegexReplacementRule("(foo)zar", () -> "$1bar");`
* Expected outcome if the document contains "foozar": "foobar"

Currently (v1.2.0) the `RegexReplacementRule` simply sets the String returned by the supplier. 

In other words, behavior similar to `String#replaceAll(String, String)` respectively `Matcher#replaceAll(String)` would be nice.

**Comment by ingomohr** [comment]
#### Change
- Bumped version to 1.4.0-SNAPSHOT
- Changed JUnit to 5.5 and Mockito to 3.7.7
- Updated the unit tests for the rule to BDD style (for better readability)
- Fixed bug that the rule also modified the given Text object if it doesn't apply to the Text at all

Todo: introduce requested feature.

**Comment by ingomohr** [comment]
/w @martinschemel 
* We want to change the existing behavior so that the value supplier is understood to supply a regex.
* Version goes up to 2.0

**Comment by ingomohr** [comment]
#### Change
* Rule does now support regex values
* Added more tests
* Version is 2.0.0-SNAPSHOT
