### ISSUE TITLE
Support Passing Writer-Constructor-Parameter-Values to Rule-Constructors in #initRules

### ISSUE THREAD

**Issue by martinschemel** [ingomohr/docwriter#28]
In a concrete writer you have to implement the abstract method `org.ingomohr.docwriter.docx.AbstractRuleBasedDocxWriter.initRules()`. Since this method is called by the no-args-constructor of the `AbstractRuleBasedDocxWriter` (which is called before the constructor of the concrete writer is called) it's not possible to access parameters passed to the constructor of your concrete writer instance.

**Example:** (see comment in `#initRules`)
```java
class MyWriter extends org.ingomohr.docwriter.docx.AbstractRuleBasedDocxWriter {

   final Object param;

   MyWriter (Object pParam) {
      this.param = pParam;
   }

   @Override
   protected List<DocumentRule> initRules() {
       // I cannot do something like "new MyRule(param);" because param is not yet set at this time.
      return Collections.emptyList();     
   }
}
```

**Workaround:**
Override `de.biotronik.biodocwriter.docs.documents.AlmDocumentPlaceholderReplaceWriter.modifyDoc(WordprocessingMLPackage)` with something like this:

```java
   @Override
   protected void modifyDoc(WordprocessingMLPackage pDoc) {
	   super.modifyDoc(pDoc);
	   new MyRule(param).apply(pDoc);
   }
```

while the `#initRules` method returns an empty list as shown in the first snippet.

**Comment by ingomohr** [comment]
Subclasses of ``AbstractRuleBasedWriter``can now call ``init()`` themselves and suppress automatic initialization at construction time.
