### ISSUE TITLE
First Line Always Empty

### ISSUE THREAD

**Issue by martinschemel** [ingomohr/docwriter#33]
It seems that the first line of a document generated with the `AbstractRuleBasedDocxWriter` always is empty and there is no way to avoid it.

#### Reproduction
* Execution the following code with this input document: [template.docx](https://github.com/ingomohr/docwriter/files/5292516/template.docx) 
   * The document is empty. I pressed `CTRL`+`A` to select everything and `DEL` to delete just to make sure.

```
import static java.util.Arrays.asList;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import org.ingomohr.docwriter.DocWriterException;
import org.ingomohr.docwriter.docx.AbstractRuleBasedDocxWriter;
import org.ingomohr.docwriter.docx.rules.DocumentRule;
import org.ingomohr.docwriter.docx.rules.MarkdownAppenderRule;

public class MyWriter extends AbstractRuleBasedDocxWriter {

	public static void main(String[] args) {
		Path in = Paths.get("<path to template.docx>");
		Path out = Paths.get(System.getProperty("user.home") + "/Desktop/my-doc.docx");
		try {
			final MyWriter writer = new MyWriter();
			writer.write(in, out);
		} catch (DocWriterException e) {
			e.printStackTrace();
		}
	}

	@Override
	protected List<DocumentRule> initRules() {
		return asList(new MarkdownAppenderRule(() -> "Hello _World_!"));
	}
}
```

##### Screenshot of Output Document:
![image](https://user-images.githubusercontent.com/1593923/94438310-3d9c1880-019f-11eb-8c45-6690905a1336.png)

I think the empty first line shouldn't be there.

**Comment by ingomohr** [comment]
Hey @martinschemel, thx for the feedback.
Yep, this looks like a bug.

**Comment by ingomohr** [comment]
w/ @martinschemel We reject this one. The behavior seems to be caused in FlexMark which we use for our component. For now, the behavior is no problem we need to fix .
