### ISSUE TITLE
Please Support Java 8 Again

### ISSUE THREAD

**Issue by ahmad2702** [ingomohr/docwriter#73]
We want to use docwriter in our java 8 project. But docwriter requires java 17. 

From my analysis, in order to make docwriter compatible with java 8 again, it is required...
* to downgrade docx4j-JAXB-ReferenceImpl to version 8.3.4, which works with java 8. 
* to update maven.compiler.source/maven.compiler.target from pom.xml and .settings/org.eclipse.jdt.core.prefs
* to remove the java 17 syntax from org.ingomohr.docwriter.docx.SimpleDocxProcessor and org.ingomohr.docwriter.docx.examples.DocWriterExampleForSimpleDocxProcessorHorizontalRule
Tested on my local machine. All unit tests passed.

Please support java 8 as before :)

**Comment by ingomohr** [comment]
Thanks @ahmad2702 for creating the ticket! Will do ^^

**Comment by ingomohr** [comment]
### Change
* Reverted Java settings to Java 7
* Replaced docx4j dependency with 8.3.8 (latest version for Java 8)
* Refactored code to not use var and multiline strings anymore

### Tests
* CI ✅ 
* Ran example for horizontal rule => horizontal rule was visible on document as expected ✅
